### PR TITLE
Update to k3os v0.2

### PR DESCRIPTION
**Pull request by wolcen**
To small PRs! :clinking_glasses:  Ty for getting this in the directory of boxes.

### CODE REVIEW

**Comment by wolcen** [comment]
Whoops - will grab md5. Doh.

**Comment by wolcen** [comment]
Change in image needs some corresponding boot script changes. Making an attempt at corrections.

**Comment by wolcen** [comment]
After reverting to 0.20-rc4, I could not verify the intent of the extra keys after specifying a template (i.e. `,"N","<enter>","{{user `password`}}","<enter>","{{user `password`}}","<enter>","1","<enter>","<enter>"`). It seems all that input would just be ignored.

In any case, the boot time was bumped as the boot delay is 15 sec on it's own, and I now get a successful build.

Thanks!

**Comment by wjimenez5271** [comment]
@wolcen Thanks so much! I think you are right there are some extra keystrokes from legacy, I'll test it out and see what I can remove.

**Pull request merged**
